spring.jackson.date-format=yyyy-MM-dd
logging.level.ru.yandex.practicum.filmorate=TRACE
logging.file.name=logs/logs.log
logging.level.org.zalando.logbook=TRACE
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
# в jdbc-url укажите путь к файлу базы данных
spring.datasource.url=jdbc:h2:file:./db/filmorate;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=taroom
spring.datasource.password=123123

