CREATE TABLE IF NOT EXISTS "user"
(
    user_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(100) NOT NULL UNIQUE,
    login    varchar(50)  NOT NULL UNIQUE,
    birthday date,
    name     varchar(100)
);

CREATE TABLE IF NOT EXISTS friendship_status
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_friendship
(
    user_id   bigint NOT NULL,
    friend_id bigint NOT NULL,
    status_id bigint NOT NULL,
    CONSTRAINT pk_user_friendship PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_user_friendship_user FOREIGN KEY (user_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_user_friendship_friend FOREIGN KEY (friend_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_user_friendship_status FOREIGN KEY (status_id) REFERENCES friendship_status (id)
);

CREATE TABLE IF NOT EXISTS rating
(
    rating_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating    varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    film_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(200) NOT NULL,
    description  text,
    release_date date         NOT NULL,
    duration     int          NOT NULL,
    rating_id    bigint       NOT NULL,
    CONSTRAINT fk_film_rating FOREIGN KEY (rating_id) REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    user_id bigint NOT NULL,
    film_id bigint NOT NULL,
    CONSTRAINT pk_film_likes PRIMARY KEY (user_id, film_id),
    CONSTRAINT fk_film_likes_user FOREIGN KEY (user_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_film_likes_film FOREIGN KEY (film_id) REFERENCES film (film_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre    varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_to_genres
(
    film_id  bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT pk_film_to_genres PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_to_genres_film FOREIGN KEY (film_id) REFERENCES film (film_id),
    CONSTRAINT fk_film_to_genres_genre FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
);
